### PR TITLE
Create harbour-upanddown-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

Hi,
Thanks for this nice app! There's still some translation strings missing though...

Menu entry "settings"
Settings hint "Enable/Disable haptic feedback" and "Enable/Disable audio feedback"
Caption "save as"

eson

### CODE REVIEW

**Comment by mMjMm** [comment]
Thank you very much. 
added also the missing strings. Hope it worked (still feeling new to github and qml...)

**Comment by eson57** [comment]
It worked fine for the master harbour-upanddown.ts, but you should try to merge changes also into translations, thank you. I created new pull request for the changes.

**Comment by mMjMm** [comment]
hello eson, 
I've messed things up...
but I am trying hard to resolve them!
Firstly there was a problem with some (conflict) files caused by my owncloud server. That messed up the .ts files...
Secondly:
I did some changes in the About.qml. (Text warping. Now also the German translation with the long sentences will work...) So maybe you take a last look on the changes? 
Thirdly:
Still a noob and git and github have still some mysteries for me! I think I've made a merge conflict... So be patient with me...
Anyway thank you for your effort. I really appreciate it!

**Comment by eson57** [comment]
Don't worry! GitHub has a certain amount of learning time for everyone, and you are the one doing the hard work here. :+1:

**Comment by mMjMm** [comment]
Hey thank you...
Your translation is merged with the master... And I am sure I will figure out the rest (branches, forks commits, pulls, pushes etc.) also in some time...
The intention of this whole project was exactly that! A learning environment to get started (and make mistakes!!!)
How should I mention you in the description? with eson57 ? and link to your github account?

**Comment by eson57** [comment]
Anyway you desire is okay. If you want to use my real name and website, that's okay to.

**Pull request merged**
